version: "3.1"

services:
  magento:
    build: .
    ports:
      - 80:80
    links:
      - db
      - elastic

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306/tcp"
    environment:
      MYSQL_DATABASE: magento_24
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root

  elastic:
    image: elasticsearch:7.9.2
    ports:
     - 9200:9200
     - 9300:9300
